language: android
android:
  components:
    - build-tools-26.0.2
    - android-26
    - android-27
    - extra
before_install:
    - chmod +x gradlew
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'build-tools-.+'
